name: windows_tests_sqlite_and_common

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      TEST_SKIP_POSTGRES: 1
      TEST_SKIP_SQLSERVER: 1
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'
    - name: md1
      run: md bin
    - name: md2
      working-directory: bin
      run: md nuget_source
    - name: dotnet test sqlite only
      working-directory: SogePoco
      run: dotnet test --configuration Release
